version: "3.8"
services:
  postgres:
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=my_music
      - POSTGRES_PASSWORD=my_music
      - POSTGRES_DB=my_music
