name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1

      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.9

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma types
        run: pnpm prisma:generate

      - name: Run ESLint
        run: pnpm lint

      - name: Run build
        run: pnpm build
