export * from "./enums";
export * from "./Album";
export * from "./Source";
export * from "./Query";
export * from "./Mutation";
export * from "./inputs";
export * from "./FirstPlayed";
export * from "./AlbumPerYearCount";
export * from "./scalars";
